document.write(" <center><h2>Name: Muhammad hasnain</h2></center>")
document.write(" <center><h2>Addres:liquetabad karachi</h2></center>")
document.write(" <center><h2>Contect no:03182400855</h2></center>")
document.write(" <center><h2>Email:mrhasnain216gamil.come</h2></center><br><br>")
document.write("<h2>Objective</h2>")
document.write("To seek a challenging position in a repotable progressive and growing organization.")
document.write("<h2>Qualification</h2>")
document.write("Matric of sindh bord")
document.write("<h2>Skills</h2>")
document.write("1)Digital markiting <br>2)web deveolopment <br> 3)Ms Power Point <br> 4)Freelancing")
document.write("<h2>Work experience</h2>")
document.write("Three year for medical feld")
document.write("<h2>Personal information</h2>")
document.write("full name:Muhammad hasnain<br> Date of birth:15/2/2007<br>Nationality:Pakistan<br>Religion:islam")
document.write("<h2>Reference</h2>")
document.write("Will be furnish on request")